services:
  backend:
    build: ./backend
    command: "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
  react:
    build: ./frontend
    command: "npm start"
    volumes:
      - ./frontend:/code
    ports:
      - "3000:3000"
