# Generated by Django 2.0.5 on 2018-06-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('user', 'search_phrase')},
        ),
    ]
