# Generated by Django 2.0.5 on 2018-06-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alert_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='interval',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
