# Generated by Django 2.0.5 on 2018-06-13 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0006_auto_20180210_1226'),
        ('main', '0006_auto_20180611_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='id',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='is_active',
        ),
        migrations.AddField(
            model_name='alert',
            name='periodictask_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.PeriodicTask'),
            preserve_default=False,
        ),
    ]
